---
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      navbar-bg: "#3ADAC6"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

Intro
==========================

### ABOUT THE PROJECT

Column {data-width = 55}
-------------------------

In this project, we analyze Nobel Prize data collected from the official Nobel Prize API.  
Our dataset contains information about laureates such as:

- Age
- Gender
- Birth country
- Prize category
- Prize amount
- Year awarded

The goal of this project is to explore historical trends and identify possible inequalities in Nobel Prize awards across time, gender, and regions of the world.
-------------------------

### DATA SOURCES

we accessed our data from the Nobel Prize website

- [Website](https://www.nobelprize.org/) 

- [Page with the API](https://www.nobelprize.org/about/developer-zone-2/)

- [API](https://api.nobelprize.org/2.1/laureates)

-------------------------

**Link to Github**
 
[code] ()
 
Patterns
==========================

Inputs {.sidebar}
-------------------------


```{r, echo=FALSE}
library(tidyverse)

Nobel <- read_csv("Nobel_final_Data.csv")

ggplot(Nobel, aes(x = Prize_year)) +
  geom_histogram() +
  labs(
    title = "Distribution of Nobel Laureates Over Time",
    x = "Year",
    y = "Count")
```

Column 
-------------------------

### Nobel Prizes by Gender & Period

```{r echo = FALSE}
library(ggplot2)
library(dplyr)

nobel <- Nobel |>
  mutate(Cent = case_when(
    Prize_year >= 1901 & Prize_year <= 1925 ~ "1901-1925",
    Prize_year >= 1926 & Prize_year <= 1950 ~ "1926-1950",
    Prize_year >= 1951 & Prize_year <= 1975 ~ "1951-1975",
    Prize_year >= 1976 & Prize_year <= 2000 ~ "1976-2000",
    Prize_year >= 2001 & Prize_year <= 2025 ~ "2001-2025"
  )) |>
  drop_na(Gender)

ggplot(nobel, aes(x = Cent, fill = Gender)) +
  geom_bar(position = "fill") +
  labs(title = "Nobel Prizes by Gender & Period", x = "time frame", y = "proportion")
```

Men have received the most awards throughout the years. More than 80% percents of the laureates are males. The number of women Nobel Prize winners has increased in the past half century but they are still evidently low.  

-------------------------

### Nobel Prizes by category & Period

```{r echo = FALSE}
library(ggplot2)
library(dplyr)

nobel <- nobel |>
  mutate(Category = fct_rev(fct_infreq(Category)))

ggplot(nobel, aes(x = Cent, fill = Category)) +
  geom_bar(position = "fill") +
  labs(title = "Nobel Prizes by Gender & Period", x = "time frame", y = "proportion") +
  theme_classic() +
  scale_fill_viridis_d()
```

New emerging categories such as economic sciences, literature is declining 

Tidyverse
==========================

Inputs {.sidebar}
-------------------------

```{r, echo=FALSE}
inputPanel(
  selectInput("n_breaks2", label = "Number of bins:",
              choices = c(5, 10, 15, 20, 25, 30), selected = 15),
  
  sliderInput("bw_adjust2", label = "Bandwidth adjustment:",
              min = 0.1, max = 3, value = 1.2, step = 0.1)
)
```

Column 
-------------------------

### Age distribution

```{r, echo=FALSE}
renderPlot({
  ggplot(nobel, aes(x = Age)) +
    geom_histogram(aes(y = after_stat(density)), 
                   bins = as.numeric(input$n_breaks2),
                   fill = "white", colour = "black") +
    geom_density(adjust = input$bw_adjust2, colour = "blue") +
    labs(x = "Age", title = "Age distribution")
})
```


