---
title: "you_the_birthday"
format: pdf
---

```{r}
library(tidyverse)
library(rvest)
library(lubridate)
```


```{r}

# step 1 : getting the dates

# making January 1st of this year as the start date and today's date as the end date
start_date <- as.Date(paste0(year(Sys.Date()), "-01-01"))
end_date <- Sys.Date()

# oultine all the days from jan 1st to today's date but keeps only saturdays(seventh day of the week in lubridate) because that is when the billboard updates
all_days <- seq.Date(start_date, end_date, by = "day")
chart_dates <- all_days[wday(all_days, label = FALSE) == 7] 

chart_dates # list of all the Saturdays from Jan 1st till today

```


```{r}
 
# step 2: making a function to scrape the Billboard data specified chart dates

#making custom links based on specified chart dates

get_billboard_chart <- function(chart_date) {
  url <- paste0("https://www.billboard.com/charts/hot-100/", chart_date, "/")
  
# read the content of the webpage and extract song related information
  
  page <- read_html(url)
  
  songs <- page %>% html_elements("li ul li")
 
# extracting  existing song title stored in the h3 node and get rid of the white spaces, if the title is not there then it is recorded as an NA 
  
  songs_df <- songs %>%
    map_df(~{
      title_node <- .x %>% html_node("h3")
      title <- if (!is.na(title_node)) html_text(title_node, trim = TRUE) else NA_character_
 
# extracting artist name  located in the span element and removing the white spaces
                
      artist_vec <- .x %>%
        html_elements("span") %>%
        html_text(trim = TRUE)
      
      artist_vec <- artist_vec[artist_vec != ""]
      artist <- if (length(artist_vec) > 0) artist_vec[1] else NA_character_

# make a tibble for each song  
       
      tibble(
        song_title = title,
        artist = artist
      )
    }) %>%
    
 # removing the rows with empty or missing row titles and adding the ranking based on position in list and convert make proper date formating, finally all this information is stored in a single data frame 
     
    filter(!is.na(song_title), song_title != "") %>%
    mutate(
      rank = row_number(),
      chart_date = as.Date(chart_date)
    )
  
  songs_df
}
```

```{r}

#step 3 : applying the function from step 2 to the specified dates in step 1 and getting one data set

#making a data frame list for every date

charts_list <- map(chart_dates, get_billboard_chart)

# combining all the data frames into one large data set by combining the rows

all_charts <- bind_rows(charts_list)

```


```{r}
#step 4 : making a csv file from the data set in step 3

write_csv(all_charts, "billboard_hot100_2026.csv")
```


